project/myproject/urls.py
from django.conf import settings  # Импортируем модуль настроек Django
from django.conf.urls.static import \
    static  # Импортируем функцию static для обработки статических файлов
from django.contrib import admin  # Импортируем модуль администратора Django
from django.urls import \
    path  # Импортируем функцию path для определения маршрутов URL
from django.views.generic import \
    RedirectView  # Импортируем класс RedirectView для перенаправления URL

from .views import (  # Импортируем представления (views) из текущего пакета
    add_files, auth, create_nomenclature, file_download, get_all_files, logout,
    main, nomenclature_detail, pageNotFound, profile, reg, replace_file,
    save_nomenclature)

# Определяем маршруты URL
urlpatterns = [
    path('', main, name='main'),  # Главная страница
    path('login', RedirectView.as_view(
        url='/login/', permanent=True)),  # Перенаправление на страницу входа
    path('login/', auth, name='login'),  # Страница входа
    path('reg', RedirectView.as_view(
        url='/reg/',
        permanent=True)),  # Перенаправление на страницу регистрации
    path('reg/', reg, name='reg'),  # Страница регистрации
    path('admin/', admin.site.urls),  # URL для административной панели Django
    path('logout/', logout),  # URL для выхода из системы
    path('profile', RedirectView.as_view(
        url='/profile/',
        permanent=True)),  # Перенаправление на страницу профиля
    path('profile/', profile, name='profile'),  # Страница профиля
    path('nomenclature_info/<str:link>/',
         nomenclature_detail,
         name='nomenclature_detail'),  # Информация о номенклатуре
    path('nomenclature/add/', create_nomenclature,
         name='create_nomenclature'),  # Страница создания номенклатуры
    path('nomenclature/add_files/<str:link>/', add_files,
         name='add_files'),  # Загрузка файлов для номенклатуры
    path('nomenclature/save/', save_nomenclature,
         name='save_nomenclature'),  # Сохранение номенклатуры
    path('file_download/<str:filename>/', file_download,
         name='file_download'),  # Загрузка файла
    path('get_all_files/', get_all_files,
         name='get_all_files'),  # Получение списка всех файлов
    path('replace_file/', replace_file, name='replace_file'),  # Замена файла
]

# Если DEBUG режим включен в настройках Django, добавляем URL для обработки статических файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound  # Устанавливаем обработчик для ошибки 404 (страница не найдена)

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myproject.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/myproject/models.py
import random  # Модуль для генерации случайной строки
import string  # Модуль для работы со строками

from django.db import models  # Модуль базы данных Django
from django.db.models.signals import (
    post_delete,  # Модуль сигналов Django
    post_save,
    pre_delete)
from django.dispatch import receiver  # Модуль обработчиков сигналов Django


# Класс пользователь
class User(models.Model):
    login = models.CharField('Логин', max_length=50)
    password = models.CharField('Пароль', max_length=50)
    email = models.EmailField('Почта', max_length=120)
    surname = models.CharField('Фамилия', max_length=40)
    name = models.CharField('Имя', max_length=35)
    patronymic = models.CharField('Отчество', max_length=45)
    phone = models.CharField('Телефон', max_length=18)
    department = models.IntegerField('Отдел')

    # Функция для отображения объектов класса в административной панели Django
    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


def generate_random_link():
    # Функция для генерации случайной строки
    characters = string.ascii_letters + string.digits
    random_link = ''.join(random.choice(characters) for _ in range(10))
    return random_link


#  Класс номенклатура
class Nomenclature(models.Model):
    name = models.CharField('Название номенклатуры', max_length=255)
    create_date = models.DateTimeField("Дата и время создания",
                                       auto_now=False,
                                       auto_now_add=False)
    status = models.BooleanField('Статус', default=False)
    create_by = models.ForeignKey(User, on_delete=models.CASCADE)
    files = models.ManyToManyField('File')
    link = models.CharField('Сгенерированная ссылка',
                            max_length=10,
                            editable=False)

    class Meta:
        """
        Функция для отображения объектов класса в административной панели Django
        """
        verbose_name = 'Номенклатура'
        verbose_name_plural = 'Номенклатуры'

    def save(self, *args, **kwargs):
        """
        Переопределение метода сохранения модели Nomenclature.
        Генерирует случайную ссылку перед сохранением объекта в базе данных.
        """
        if not self.link:
            self.link = generate_random_link()
        super().save(*args, **kwargs)


class File(models.Model):
    name = models.CharField('Название файла', max_length=100)
    file = models.FileField('Адрес файла', upload_to='files/')
    status = models.BooleanField('Статус', default=False)

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """
        Переопределение метода сохранения модели File.
        Вызывает обновление статуса номенклатуры после сохранения файла.
        """
        super().save(*args, **kwargs)
        self.update_nomenclature_status()

    def update_nomenclature_status(self):
        """
        Обновляет статус номенклатуры на основе статусов файлов, связанных с ней.
        """
        has_files_with_false_status = self.nomenclature_set.filter(
            files__status=False).exists()
        self.nomenclature_set.update(status=not has_files_with_false_status)


def set_nomenclature_link(sender, instance, **kwargs):
    """
    Сигнальная функция для установки сгенерированной ссылки для объекта Nomenclature перед сохранением.
    """
    if not instance.link:
        instance.link = generate_random_link()


@receiver(post_save, sender=(File, Nomenclature))
def handle_file_update(sender, instance, **kwargs):
    """
    Сигнальная функция для обновления статуса номенклатуры после сохранения или обновления файла или номенклатуры.
    """
    instance.update_nomenclature_status()


@receiver(post_delete, sender=Nomenclature)
@receiver(pre_delete, sender=Nomenclature)
def delete_files(sender, instance, **kwargs):
    """
    Сигнальная функция для удаления файлов, связанных с объектом Nomenclature, перед или после удаления.
    """
    files = instance.files.all()
    for file in files:
        file.file.delete(save=False)


@receiver(pre_delete, sender=Nomenclature)
def delete_associated_files(sender, instance, **kwargs):
    """
    Сигнальная функция для удаления связанных файлов, связанных с объектом Nomenclature, перед удалением.
    """
    files = instance.files.all()
    for file in files:
        file.delete()


post_delete.connect(delete_files, sender=Nomenclature)

project/myproject/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    login = forms.CharField(max_length=50, help_text='Логин')
    password = forms.CharField(max_length=50, help_text='Пароль')

project/myproject/views.py
from django.contrib import messages  # Импортируем модуль сообщений Django
from django.contrib.auth.hashers import (  # Импортируем функции для работы с паролями
    check_password, make_password)
from django.contrib.auth.models import \
    User  # Импортируем модель пользователя Django
from django.http import HttpResponseNotFound  # Импортируем классы HTTP-ответов
from django.http import (FileResponse, HttpResponse, HttpResponseRedirect,
                         JsonResponse)
from django.shortcuts import (  # Импортируем функции для работы с запросами и шаблонами
    get_object_or_404, redirect, render)
from django.urls import \
    reverse  # Импортируем функцию reverse для генерации URL-адресов

from .models import *  # Импортируем модели из текущего пакета


# Функция представления для авторизации
def auth(request):
    if request.method == "POST":
        login = request.POST.get("login")
        password = request.POST.get("password")
        user = User.objects.filter(login=login).first()

        if user and check_password(password, user.password):
            response = redirect('http://127.0.0.1:8000/')
            response.set_cookie('login', user.login)
            response.set_cookie('entry', '1')
            return response

    return render(request, 'webapp/authorization.html')


# Функция представления для профиля пользователя
def profile(request):
    a = User.objects.get(login=request.COOKIES.get('login'))
    return render(request, 'webapp/profile.html', {"user": a})


# Функция представления для регистрации
def reg(request):
    if request.method == "POST":
        login = request.POST.get("login")
        user, created = User.objects.get_or_create(
            login=login,
            defaults={
                "password": make_password(request.POST.get("password")),
                "email": request.POST.get("email"),
                "name": request.POST.get("name"),
                "surname": request.POST.get("surname"),
                "patronymic": request.POST.get("patronymic"),
                "phone": request.POST.get("phone_number"),
                "department": request.POST.get("department"),
            })

        if not created:
            return HttpResponse("Пользователь с таким логином уже существует.")

        response = redirect('http://127.0.0.1:8000/')
        response.set_cookie('entry', '1')
        response.set_cookie('login', user.login)
        return response

    return render(request, 'webapp/registration.html')


# Функция представления для выхода из системы
def logout(request):
    response = HttpResponseRedirect('http://127.0.0.1:8000/')
    response.delete_cookie('entry')
    response.delete_cookie('login')
    return response


# Главная функция представления
def main(request):
    nomenclature = Nomenclature.objects.prefetch_related('files')
    for item in nomenclature:
        item.status = all(file.status for file in item.files.all())

    return render(request, 'webapp/body.html', {'nomenclature': nomenclature})


# Функция представления для деталей номенклатуры
def nomenclature_detail(request, link):
    nomenclature = get_object_or_404(Nomenclature, link=link)
    files = nomenclature.files.all()
    return render(request, 'webapp/nomenclature_detail.html', {
        'nomenclature': nomenclature,
        'files': files
    })


# Функция представления для создания номенклатуры
def create_nomenclature(request):
    if request.COOKIES.get('entry') == '1':
        return render(request, 'webapp/create_nomenclature.html')
    else:
        return redirect(reverse('login'))


# Функция представления для сохранения номенклатуры
def save_nomenclature(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        create_date = request.POST.get('create_date')
        files = request.FILES.getlist('files')

        # Проверяем расширения файлов
        allowed_extensions = ('.xlsx', '.xls')
        invalid_files = [
            file.name for file in files
            if not file.name.lower().endswith(allowed_extensions)
        ]
        if invalid_files:
            messages.error(
                request,
                f'Invalid file(s) found: {", ".join(invalid_files)}. Only .xlsx and .xls files are allowed.'
            )
            return redirect('create_nomenclature')

        try:
            login_cookie = request.COOKIES.get('login')
            user = User.objects.get(login=login_cookie)
        except User.DoesNotExist:
            return redirect(reverse('login'))

        nomenclature = Nomenclature.objects.create(name=name,
                                                   create_date=create_date,
                                                   create_by=user)

        for file in files:
            file_object = File.objects.create(name=file.name, file=file)
            nomenclature.files.add(file_object)

        return redirect('http://127.0.0.1:8000/')

    return render(request, 'create_nomenclature.html')


# Функция представления для загрузки файла
def file_download(request, filename):
    nomenclature = get_object_or_404(Nomenclature, file__name=filename)
    file_path = nomenclature.file.path
    return FileResponse(open(file_path, 'rb'), as_attachment=True)


# Функция представления для добавления файлов к номенклатуре
def add_files(request, link):
    if request.COOKIES.get('entry') == '1':
        nomenclature = get_object_or_404(Nomenclature, link=link)
        if request.method == 'POST':
            files = request.FILES.getlist('files')
            for file in files:
                if not file.name.lower().endswith(('.xlsx', '.xls')):
                    messages.error(request,
                                   'Only .xlsx and .xls files are allowed.')
                    return redirect('nomenclature_detail', link=link)

                file_object = File.objects.create(name=file.name, file=file)
                nomenclature.files.add(file_object)

            return redirect('nomenclature_detail', link=link)

        return render(request, 'webapp/add_files_popup.html',
                      {'nomenclature': nomenclature})
    else:
        return redirect(reverse('login'))


# Функция представления для получения всех файлов
def get_all_files(request):
    files = File.objects.filter(status=True)
    file_list = []
    for file in files:
        file_data = {
            'name': file.name,
        }
        file_list.append(file_data)
    return JsonResponse(file_list, safe=False)


# Функция представления для замены файла
def replace_file(request):
    files = request.FILES.getlist('files')
    if request.method == 'POST':
        original_file_id = request.POST.get('originalFileId')
        similar_file_name = request.POST.get('similarFileName')

        try:
            original_file = File.objects.get(id=original_file_id)
            similar_file = File.objects.get(name=similar_file_name)
            Nomenclature.files.through.objects.filter(
                file_id=original_file.id).update(file_id=similar_file.id)
            Nomenclature.update_status()

            return JsonResponse({
                'success': True,
                'message': 'File replaced successfully',
            })
        except File.DoesNotExist:
            return JsonResponse({
                'success': False,
                'message': 'File not found',
            })
    else:
        return JsonResponse({
            'success': False,
            'message': 'Invalid request method',
        })


# Функция представления для обработки страницы 404
def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

project/myproject/templates/webapp/add_files_popup.html
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <form method="post" action="{% url 'add_files' link=nomenclature.link %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mb-4 mt-2">
                    <input type="file" class="form-control-file" id="id_files" name="files" accept=".xlsx, .xls" multiple required>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Загрузить файл</button>
                </div>
            </form>
        </div>
    </div>
</div>

project/myproject/templates/webapp/authorization.html
{% extends "webapp/main.html" %}

{%block title%}<title>Служба аутентификации</title>{% endblock %}

{% block body%}
<div class="form-container shadow rounded">
    <div class="background">
        <form method="post">
            {% csrf_token %}
            <button id="close-button-login" type="button" class="btn-close"
                aria-label="Закрыть"></button>
            <div class="form-group">
                <label class="user-select-none" for="exampleInputEmail1">Логин</label>
                <input name="login" type="text" class="form-control border"
                    id="exampleInputEmail1"
                    aria-describedby="emailHelp" placeholder="Введите логин"
                    required>
            </div>
            <div class="form-group">
                <label class="user-select-none" for="exampleInputPassword1">Пароль</label>
                <input name="password" type="password" class="form-control
                    border rounded"
                    id="exampleInputPassword1" placeholder="Введите пароль"
                    required>
            </div>
            <div class="col align-self-center">
                <button id="EntryButton" type="submit" class="btn btn-primary">Войти</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementById("close-button-login").onclick = function () {
        window.location.assign("http://127.0.0.1:8000/");
    }

    document.getElementById("EntryButton").onclick = function () {
        let LoginInput = document.getElementById("exampleInputEmail1");
        let PasswordInput = document.getElementById("exampleInputPassword1");

        if (LoginInput.value != "" || PasswordInput.value != "") {
            let toastElList = [].slice.call(document.querySelectorAll('.toast'))
            let toastList = toastElList.map(function (toastEl) {

                return new bootstrap.Toast(toastEl)
            })
            toastList.forEach(toast => toast.show())
        }
    }

</script>
{% endblock %}

project/myproject/templates/webapp/body.html
{% extends "webapp/main.html" %}
{% block title %}
<title>Главная</title>
{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center mt-3 mb-5">Номенклатура</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr class="text-center table-primary user-select-none">
                        <th scope="col">
                            Название
                            <span class="sort-icon"></span>
                        </th>
                        <th scope="col">
                            Дата создания
                            <span class="sort-icon"></span>
                        </th>
                        <th scope="col">
                            Статус
                            <span class="sort-icon"></span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in nomenclature %}
                    <tr>
                        <td class="text-truncate">
                            <a href="{% url 'nomenclature_detail' item.link %}">{{ item.name }}</a>
                        </td>
                        <td class="text-truncate">{{ item.create_date }}</td>
                        <td class="text-center text-truncate">
                            {% if item.status %}
                            <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                            <i class="fas fa-times-circle text-danger"></i>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-12 sticky-top text-center">
            <a class="btn btn-primary" href="{% url 'create_nomenclature' %}"
                id="add-item-button">Добавить
                номенклатуру</a>
        </div>
    </div>
</div>
<script>
    const table = document.querySelector('.table');
    const headers = table.querySelectorAll('th');
    headers.forEach(header => {
        header.addEventListener('click', () => {
            const tableRows = Array.from(table.querySelectorAll('tbody tr'));
            const index = Array.from(header.parentNode.children).indexOf(header);
            const isAscending = header.classList.contains('ascending');
            tableRows.sort((a, b) => {
                const aValue = a.querySelector(`td:nth-child(${index + 1})`).textContent.trim();
                const bValue = b.querySelector(`td:nth-child(${index + 1})`).textContent.trim();
                return aValue.localeCompare(bValue, 'en', { numeric: true, sensitivity: 'base' });
            });
            if (isAscending) {
                tableRows.reverse();
                header.classList.remove('ascending');
                header.classList.add('descending');
            } else {
                headers.forEach(header => {
                    header.classList.remove('ascending', 'descending');
                });
                header.classList.add('ascending');
            }
            tableRows.forEach(row => table.querySelector('tbody').appendChild(row));
            updateSortIcons();
        });
    });
    
    // Update the sorting icons
    function updateSortIcons() {
        const sortIcons = document.querySelectorAll('.sort-icon');
        sortIcons.forEach(sortIcon => {
            const header = sortIcon.parentNode;
            if (header.classList.contains('ascending')) {
                sortIcon.innerHTML = '<i class="fas fa-sort-up"></i>';
            } else if (header.classList.contains('descending')) {
                sortIcon.innerHTML = '<i class="fas fa-sort-down"></i>';
            } else {
                sortIcon.innerHTML = '';
            }
        });
    }
</script>
{% endblock %}

project/myproject/templates/webapp/create_nomenclature.html
{% extends "webapp/main.html" %}
{% block title %}
<title>Номенклатура</title>
{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center mt-3 mb-5">Добавление номенклатуры</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-6 offset-3">
            {% if messages %}
            <div class="messages text-bg-warning rounded">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    <i class="fas fa-exclamation-triangle"></i>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form method="post" action="{% url 'save_nomenclature' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="id_name">Название номенклатуры</label>
                    <input type="text" class="form-control" id="id_name" name="name" placeholder="Важный документ №1" required>
                </div>
                <div class="form-group mb-3">
                    <label for="id_create_date">Дата и время создания</label>
                    <input type="datetime-local" class="form-control" id="id_create_date" name="create_date" required>
                </div>
                <div class="form-group mb-3">
                    <label for="id_files">Файлы номенклатуры</label>
                    <input type="file" class="form-control-file" id="id_files" name="files" accept=".xlsx, .xls" multiple required>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Создать</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    // Set current date and time as the default value
    var now = new Date();
    var year = now.getFullYear();
    var month = ('0' + (now.getMonth() + 1)).slice(-2);
    var day = ('0' + now.getDate()).slice(-2);
    var hours = ('0' + now.getHours()).slice(-2);
    var minutes = ('0' + now.getMinutes()).slice(-2);
    var formattedDate = `${year}-${month}-${day}T${hours}:${minutes}`;
    document.getElementById("id_create_date").value = formattedDate;
    
    var create_date = document.getElementById("id_create_date");
    create_date.addEventListener("input", function () {
        var selectedDate = new Date(create_date.value);
        var currentDate = new Date();
        if (selectedDate > currentDate) {
            create_date.setCustomValidity("Дата и время не могут быть в будущем");
        } else {
            create_date.setCustomValidity("");
        }
    });
</script>
{% endblock %}

project/myproject/templates/webapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link rel="shortcut icon" href="{% static 'main/img/favicon.ico' %}"
            type="image/x-icon">
        <!-- Include styles -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <link href="https://bootstrap-4.ru/docs/5.3/assets/css/docs.css"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
        <link rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://unpkg.com/imask"></script>
        <!-- Window title -->
        {%block title%}{%endblock%}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" href="http://127.0.0.1:8000/">Главная</a>
                <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Переключатель навигации">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#"
                                role="button" data-bs-toggle="dropdown"
                                aria-expanded="false" id="profileLink">
                            Профиль
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end mt-1"
                                id="dropdown-menu">
                                <li id="loginItem"><a class="dropdown-item"
                                    href="http://127.0.0.1:8000/login/">Вход</a></li>
                                <li id="registerItem"><a class="dropdown-item"
                                    href="http://127.0.0.1:8000/reg/">Регистрация</a></li>
                                <li id="profileItem" style="display: none;"><a
                                    class="dropdown-item"
                                    href="http://127.0.0.1:8000/profile/">Профиль</a></li>
                                <li id="logoutItem" style="display: none;"><a
                                    class="dropdown-item"
                                    href="http://127.0.0.1:8000/logout/">Выйти
                                    из аккаунта</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {%block body%}{%endblock%}
        <script src="{% static 'main/js/scripts.js' %}"></script>
    </body>
</html>

project/myproject/templates/webapp/profile.html
{% extends "webapp/main.html" %}
{%block title%}
<title>Профиль</title>
{% endblock %}
{% block body%}
<div class="profileinfo">
    <div class="d-flex align-items-start">
        <div class="col-2 ms-4 mt-5 me-4">
            <div class="list-group" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action active
                    text-center"
                    id="list-profile-list" data-bs-toggle="list"
                    href="#list-profile" role="tab"
                    aria-controls="list-profile">Профиль</a>
            </div>
        </div>
        <div class="vr me-4"></div>
        <div class="col-8">
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="list-profile"
                    role="tabpanel"
                    aria-labelledby="list-profile-list"></div>
                <h2 class="text-center mt-3 mb-5">Профиль пользователя</h2>
                <div class="text-left">
                    <p>Фамилия: {{ user.surname }}</p>
                    <p>Имя: {{ user.name }}</p>
                    <p>Отчество: {{ user.patronymic }}</p>
                    <p>Номер телефона: {{ user.phone }}</p>
                    <p>Почта: {{ user.email }} </p>
                    <p>Номер отдела: {{ user.department }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}